
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-consumer
  template:
    metadata:
      labels:
        app: nats-consumer
    spec:
      containers:
      - name: nats-consumer
        image: nats-consumer:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nats-consumer-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: nats-consumer-app
